```{r}
# Correaltion between applied drugs and cytotoxic effect on lung cancer cells?

## Can we separate lung cancer subtypes by Principal Components

  ## filter prism data for lung cancer cell lines
diseases=prism.cl[, 20]

p_lung=c(which(diseases=="Lung Cancer"))


prism_lung=prism[p_lung,]
prism_lung

# prism data set which only contains lung cancer cell lines:     prism_lung

# check for number of lung cancer cell lines
dim(prism_lung)
```
```{r}
# Principal Component analysis with lung cancer cell lines from prism data set

# do PCA only with third dose of each medicament
## filter prism_lung_scaled for third doses

third=seq(3, 11168, by=8)

prism_3=prism_lung[,third]

dim(prism_3)


    ##-> new data set: prism_3  
    ##(third dose of each medicament with lung            cancer data)
```

```{r}
# replace NAs 
## calculate means of columns
average_column=apply(prism_3,2,mean, na.rm=TRUE)
```

```{r}
apply(prism_3, 2, replace)
```

```{r}
# use zoo package to replace all missing values by column means
library("zoo")
prism_3_replaced=na.aggregate(prism_3)

sum(is.na(prism_3_replaced))

#?????????????????????????????????????? Why are there still so many NAs?


```

```{r}
library(lattice)
library(grid)
library(survival)
library(Formula)
library(ggplot2)
install.packages(Hmisc)
library(Hmisc)
```

```{r}
column_1_imputed=
  with(prism_3, impute(prism_3[,1],mean))

sum(is.na(column_1_imputed))
#-> imputation by means of single rows does work!
```


```{r}
for(i in 1:ncol(prism_3)){
  prism_3[,i][is.na(prism_3[,i])]=mean(prism_3[,i], na.rm=TRUE)
}

sum(is.na(prism_3))
```


```{r}
apply(prism_3, 1, function(x){sum(is.na(x))})
NA_column=apply(prism_3, 2, function(x){sum(is.na(x))})
```


```{r}
# search for columns with remaining NAs
c_NA=c(prism_3[,which( NA_column>1)])
length(c_NA)
#-> in 10 columns there are missing values

c_NA
```


```{r}
# remove these 10 columns 
prism_ready=prism_3[,-which(NA_column>1)]

sum(is.na(prism_ready))

#-> prism_ready is the successfully cleaned prism data frame; it does only include those cell lines which belong to lung cancer; it does only contain the third dose of each medicament; all NAs were replaced by the mean of the corresponding column; 10 columns with only NAs have been removed 
dim(prism_new)
#-> dim= 102   1386
```


























```{r}
###??????????????????????????????
nPCs=estim_ncpPCA(prism_lung, ncp.min=0, ncp.max=100, method="Regularized", scale=TRUE, method.cv="gcv")
nPCs$ncp

completed=imputePCA(prism_lung, ncp=nPCs$ncp, scale=TRUE)
```

```{r}
# question for tutorium

# use library(missMDA)

library(missMDA)
## only use first 500 columns
### number of missing values
sum(is.na(prism_lung[,1:500]))

### optimal number of dimensions for imputation
ncp=estim_ncpPCA(prism_lung[,1:500])
ncp

### data imputation
complete=imputePCA(prism_lung[,1:500], ncp=ncp$ncp, scale=TRUE)

complete
```
```{r}
complete
as.data.frame(complete)
```


```{r}
# do PCA with completed data
library(FactoMineR)
lung_pca=PCA(complete$completeObs)
```


```{r}
# PCA
str(complete)
class(complete)
prcomp(complete)
```


```{r}
# run PCA
library(FactoMineR)
lung_pca=PCA(complete$completeObs)
```


```{r}
# compute variance of eigenvalues
lung_pca$eig

lung_pca$var$cos2
```


```{r}
lung_pca$var$contrib
```
```{r}
dimdesc(lung_pca)
```
```{r}
# install.packages("devtools")
library("devtools")
install_github("kassambara/factoextra")


library("factoextra")
fviz_pca_var(lung_pca, col.var="contrib", repel=TRUE)
```
```{r}
# get eigenvalues bigger than 1
summary(lung_pca)
lung_pca$eig
get_eigenvalue(lung_pca)
```
```{r}
# 
library(paran)
paran(lung_pca, graph=TRUE)
```


```{r}
# run PCA with prcomp()
prcomp(complete)


```


```{r}
estim_ncpPCA(prism_lung)
```

```{r}
# imupting missing values with pcaMethods
# library(pcaMethods)
##-> not possible with this version of r!
imputePCA(prism_lung, scale=TRUE, )
```

```{r}
# use prcomp for PCA
prcomp(prism_lung, na.rm)
```
```{r}
# use hotdeck() for imputing missing data
prism_lung_imputed=hot.deck(prism_lung)


```
```{r}
install.packages("pcaMethods")

```
```{r}
chooseCRANmirror()
```

```{r}
kNN(prism_lung)
```

