```{r}
# Topic 2 !
## find most effective drugs!

### have a look at Mesothelioma cell lines
diseases_subtype=prism.cl[, 21]

p_Meso=c(which(diseases_subtype=="Mesothelioma"))
p_Meso

prism_Meso=prism[p_Meso,]
dim(prism_Meso)
```


```{r}
### have a look at Small Cell Lung Cancer cell lines
diseases_subtype=prism.cl[, 21]

p_SCLC=c(which(diseases_subtype=="Small Cell Lung Cancer (SCLC)"))
p_SCLC

prism_SCLC=prism[p_SCLC,]
dim(prism_SCLC)

```

```{r}
### have a look at NSCLC cell lines
prism_NSCLC
```


```{r}
diseases=prism.cl[, 20]

p_lung=c(which(diseases=="Lung Cancer"))

p_lung

which(p_lung==54)
which(p_lung==57)
which(p_lung==74)
which(p_lung==136)
which(p_lung==142)
which(p_lung==144)
which(p_lung==243)
which(p_lung==273)
which(p_lung==125)
which(p_lung==286)
which(p_lung==324)
which(p_lung==350)
which(p_lung==352)
which(p_lung==390)
which(p_lung==404)
which(p_lung==425)
```


```{r}
prism_NSCLC=prism_lung[-125,]

dim(prism_NSCLC)
```


```{r}
prism_lung=prism[p_lung,]
prism_lung
numbers_lung=c(which(diseases_subtype=="Small Cell Lung Cancer (SCLC)"))
prism_NSCLC=prism_lung[-p_SCLC,]

dim(prism_NSCLC)
```
#############################################
```{r}
# search for most effective drugs in SCLC cell lines
prism_SCLC
```


```{r}
min=min(prism_SCLC, na.rm=TRUE)
min
which(prism_SCLC==min)
which.min(prism_SCLC)
prism[,86134]
```


```{r}
vector_SCLC=as.list(prism_SCLC)
which.min(vector_SCLC)
```


```{r}
column=apply(prism_SCLC, 2, function(x){sum(is.na(x))})

prism_SCLC_cleaned=prism_SCLC[,-which(column>10)]

dim(prism_SCLC_cleaned)

#-> NAs removen doesn´t make sense
```


```{r}
# look at mins rowwise
min(prism_SCLC[1,], na.rm=TRUE)
which.min(prism_SCLC[1,])

## test
prism_SCLC[1,3039]
###-> function which.min does work
```


```{r}
min(prism_SCLC[1,], na.rm=TRUE)
min(prism_SCLC[2,], na.rm=TRUE)
min(prism_SCLC[3,], na.rm=TRUE)
min(prism_SCLC[4,], na.rm=TRUE)
min(prism_SCLC[5,], na.rm=TRUE)
min(prism_SCLC[6,], na.rm=TRUE)
min(prism_SCLC[7,], na.rm=TRUE)
min(prism_SCLC[8,], na.rm=TRUE)
```
```{r}
which.min(prism_SCLC[1,])
which.min(prism_SCLC[2,])
which.min(prism_SCLC[3,])
which.min(prism_SCLC[4,])
which.min(prism_SCLC[5,])
which.min(prism_SCLC[6,])
which.min(prism_SCLC[7,])
which.min(prism_SCLC[8,])
```
```{r}
# most effective drugs on SCLC
# BRD-K13810148-311-03-2::10::HTS002 
                              3039 
#BRD-A66419424-001-02-4::2.5::HTS002 
                               1104 
#BRD-K12867552-001-04-7::10::HTS002 
                              2831 
#BRD-K15409150-001-05-8::10::HTS002 
                              3167 
#BRD-K15409150-001-05-8::10::HTS002 
                              3167 
#BRD-K96104201-001-01-5::10::HTS002 
                             10767 
#BRD-K39484304-001-16-5::10::HTS002 
                              5447 
#BRD-K96104201-001-01-5::10::HTS002 
                             10767 
```
#used doses: dose1, dose2, dose3, dose4, dose5, dose6, 10, 2.5
```{r}
# first drug:BRD-K13810148-311-03-2::10::HTS002 

c2=c(prism_SCLC[1,3033:3040])
c2


 
c1=c(1,2,3,4,5,6,7,8,-0.06933266,-0.8475333,-0.4299717,0.2946714,0.606078,-1.107966,-9.615792,-3.193757)
```


```{r}
# create data of first medicament an all of its 8 doses

drug1=matrix(c1, nrow=8,ncol=2, byrow=FALSE)
plot(drug1)



```
```{r}
# get information about first drug:
which(prism.treat$broad_id=="BRD-K13810148-311-03-2")
prism.treat[3273,5]
```

# no doses dependency for medicament 1 (givinostat)
###################################################

```{r}
# second drug: BRD-A66419424-001-02-4::2.5::HTS002 
                               1104 
c2=c(prism_SCLC[2,1097:1104])
c2


 
c1=c(1,2,3,4,5,6,7,8,0.7309511,0.590873,1.218204,0.3833024,0.8667794,-0.4719236,-8.701737,-9.320642)
```


```{r}
# create data of second medicament an all of its 8 doses

drug2=matrix(c1, nrow=8,ncol=2, byrow=FALSE)
plot(drug2, xlab="doses", ylab="effect of drug1 on SCLC cell lines growth")



```
# maybe dose dependency
```{r}
# test for correlation
x=c(1,2,3,4,5,6,7,8)
y=c(0.7309511,0.590873,1.218204,0.3833024,0.8667794,-0.4719236,-8.701737,-9.320642)
cor(x,y)
```

```{r}
# get information about second drug:
which(prism.treat$broad_id=="BRD-A66419424-001-02-4" )
prism.treat[1249,5]
#-> medicament: ixazomib-citrate
```

##################################################

```{r}
# third drug: BRD-K12867552-001-04-7::10::HTS002 
                              2831 
c2=c(prism_SCLC[3,2825:2832])
c2



 
c1=c(1,2,3,4,5,6,7,8,0.7686234,0.5730888,0.6686534,0.820555,1.031086,0.7536717,-8.31886,-2.357724)
```


```{r}
# create data of second medicament an all of its 8 doses

drug3=matrix(c1, nrow=8,ncol=2, byrow=FALSE)
plot(drug3, xlab="doses", ylab="effect of drug3 on SCLC cell lines growth")



```
# not dose dependency
```{r}
# test for correlation
x=c(1,2,3,4,5,6,7,8)
y=c(0.7686234,0.5730888,0.6686534,0.820555,1.031086,0.7536717,-8.31886,-2.357724)
cor(x,y)
```

```{r}
# get information about third drug:
which(prism.treat$broad_id=="BRD-K12867552-001-04-7" )
prism.treat[3074,5]
#-> medicament: PCI-24781
```

```{r}
#fourth drug:BRD-K96104201-001-01-5::10::HTS002 
                             10767 

c2=c(prism_SCLC[6,10761:10768])

# this medicament was the most effective for the 8th cell line of prism_SCLC, too
c2.2=c(prism_SCLC[8, 10761:10768])


c1=c(1,2,3,4,5,6,8,0.2609308,0.6316695,0.1250064,0.6839668,0.4557789,-0.1928866,-10.26673,-6.645097)

c1.2=c(1,2,3,4,5,6,7,8,0.4332369,0.5019201,0.4385701,0.5883302,0.1971815,-0.3786651,-10.14163,-5.28422)
```


```{r}
# create data of second medicament an all of its 8 doses

drug4=matrix(c1, nrow=8,ncol=2, byrow=FALSE)
plot(drug4, xlab="doses", ylab="effect of drug4 on SCLC cell lines growth")

drug4.2=matrix(c1.2, nrow=8,ncol=2, byrow=FALSE)
plot(drug4, xlab="doses", ylab="effect of drug4.2 on SCLC cell lines growth")



```
# not dose dependency, maybe mistake ? Why only effect with such an high dose and NA with higher dose?
```{r}
# test for correlation
x=c(1,2,3,4,5,6,7,8)
y=c(0.2609308,0.6316695,0.1250064,0.6839668,0.4557789,-0.1928866,-10.26673,-6.645097)
cor(x,y)

y.2=c(0.4332369,0.5019201,0.4385701,0.5883302,0.1971815,-0.3786651,-10.14163,-5.28422)
cor(x,y.2)
```

```{r}
# get information about fourth drug:
which(prism.treat$broad_id=="BRD-K96104201-001-01-5" )
prism.treat[10778,5]
#-> medicament: azalomycin-b
```
###################################################

```{r}
# fifth drug: BRD-K15409150-001-05-8::10::HTS002 
                              3167 
c2=c(prism_SCLC[4,3161:3168])


c2.2=c(prism_SCLC[5,3161:3168])
c2.2
 
c1=c(1,2,3,4,5,6,7,8,0.3252984,0.2691451,0.8199687
,0.2753309,-0.3301197,-1.751943,-9.612311,-4.776765)

c1.2=c(1,2,3,4,5,6,7,8,0.6296565,0.1011332,0.3341141,0.05411984,-0.4416629,-1.35251,-9.86566,-3.581259)
```


```{r}
# create data of fifth medicament an all of its 8 doses for cell line 4 and 5 of prism_SCLC 

drug5=matrix(c1, nrow=8,ncol=2, byrow=FALSE)
plot(drug5, xlab="doses", ylab="effect of drug5 on SCLC cell lines growth")

drug5.2=matrix(c1.2, nrow=8,ncol=2, byrow=FALSE)
plot(drug5.2, xlab="doses", ylab="effect of drug5.2 on SCLC cell lines growth")


```
# not dose dependency
```{r}
# test for correlation
x=c(1,2,3,4,5,6,7,8)
y=c(0.3252984,0.2691451,0.8199687
,0.2753309,-0.3301197,-1.751943,-9.612311,-4.776765)

cor(x,y)

y.2=c(0.6296565,0.1011332,0.3341141,0.05411984,-0.4416629,-1.35251,-9.86566,-3.581259)

cor(x,y.2)
```

```{r}
# get information about third drug:
which(prism.treat$broad_id=="BRD-K15409150-001-05-8" )
prism.treat[3401,5]
#-> medicament: penfluridol
```
``####################################################`
```{r}
# get more information about drugs for SCLC:
```


```{r}
# givinostat
which(prism.treat$broad_id=="BRD-K13810148-311-03-2")
#-> row 3273:3280

# proof name
prism.treat[3280,5]

# mode of action
prism.treat[3280,6]
#-> HDAC inhibitor

# target
prism.treat[3280,7]
#-> HDAC1, HDAC2, HDAC3, HDAC4, HDAC5, HDAC6, HDAC7, HDAC8, HDAC9...

# disease.area
prism.treat[3280,8]
#-> NA

# indication
prism.treat[3280,9]
#-> NA
```


```{r}
# ixazomib-citrate
which(prism.treat$broad_id=="BRD-A66419424-001-02-4")
#-> row 1249:1256

# proof name
prism.treat[1249,5]

# mode of action
prism.treat[1249,6]
#-> protease inhibitor

# target
prism.treat[1249,7]
#-> ?...

# disease.area
prism.treat[1249,8]
#-> hematologic malignancy

# indication
prism.treat[1249,9]
#-> multiple myeloma
```
```{r}
# PCI-24781
which(prism.treat$broad_id=="BRD-K12867552-001-04-7")
#-> row 3073:3080

# proof name
prism.treat[3073,5]

# mode of action
prism.treat[3073,6]
#-> HDAC inhibitor

# target
prism.treat[3073,7]
#-> HDAC1, HDAC2, HDAC3, HDAC6

# disease.area
prism.treat[3073,8]
#-> NA

# indication
prism.treat[3073,9]
#-> NA
```
```{r}
# azalomycin-b
which(prism.treat$broad_id=="BRD-K96104201-001-01-5")
#-> row 10777:10784

# proof name
prism.treat[10777,5]

# mode of action
prism.treat[10777,6]
#-> bacterial 50S ribosomal subunit inhibitor

# target
prism.treat[10777,7]
#-> NA

# disease.area
prism.treat[10777,8]
#-> NA

# indication
prism.treat[10777,9]
#-> NA
```


```{r}
# penfluridol
which(prism.treat$broad_id=="BRD-K15409150-001-05-8")
#-> row 3401:3408

# proof name
prism.treat[3401,5]

# mode of action
prism.treat[3401,6]
#-> T-type calcium channel blocker

# target
prism.treat[3401,7]
#-> CACNA1G

# disease.area
prism.treat[3401,8]
#-> neurology/psychiatry

# indication
prism.treat[3401,9]
#-> schizophrenia
```

```
sum up information about drugs for SCLC:

-> givinostat
-> ixazomib-citrate
-> PCI-24781
-> azalomycin-b
-> penfluridol



