```{r}
# Correaltion between applied drugs and cytotoxic effect on lung cancer cells?

## Can we separate lung cancer subtypes by Principal Components

  ## filter prism data for lung cancer cell lines
  ## column 20 shows diseases
diseases=prism.cl[, 20]

p_lung=c(which(diseases=="Lung Cancer"))


prism_lung=prism[p_lung,]
prism_lung

# prism data set which only contains lung cancer cell lines:     prism_lung

# check for number of lung cancer cell lines
dim(prism_lung)
```
```{r}
# Principal Component analysis with lung cancer cell lines from prism data set

# do PCA only with third dose of each medicament
## filter prism_lung_scaled for third doses!

third=seq(3, 11168, by=8)

prism_3=prism_lung[,third]

dim(prism_3)


    ##-> new data set: prism_3  
    ##(third dose of each medicament with lung            cancer data)
```

```{r}
# replace NAs 
## calculate means of columns
average_column=apply(prism_3,2,mean, na.rm=TRUE)
```



```{r}
# use zoo package to replace all missing values by column means
library("zoo")
prism_3_replaced=na.aggregate(prism_3)

sum(is.na(prism_3_replaced))

#?????????????????????????????????????? Why are there still so many NAs?


```

```{r}
# replace missing values by mean of column by hand
for(i in 1:ncol(prism_3)){
  prism_3[,i][is.na(prism_3[,i])]=mean(prism_3[,i], na.rm=TRUE)
}

sum(is.na(prism_3))

#-> still 1020 Nas left! Why?
```

```{r}
# search for columns with remaining NAs
# which columns contain NAs
NA_column=apply(prism_3,2,function(x){sum(is.na(x))})

##-> 10 columns contain only NAs -> remove 10 lines

# data set without NAs
c_NA=c(prism_3[,which( NA_column>1)])
length(c_NA)
#-> in 10 columns there are missing values

```


```{r}
# remove these 10 columns 
prism_ready=prism_3[,-which(NA_column>1)]

sum(is.na(prism_ready))

#-> prism_ready is the successfully cleaned prism data frame; it does only include those cell lines which belong to lung cancer; it does only contain the third dose of each medicament; all NAs were replaced by the mean of the corresponding column; 10 columns with only NAs have been removed 
dim(prism_new)
#-> dim= 102   1386
```


```{r}
# run PCA with prism_new data frame

## with prcomp()
prism_PCA=prcomp(prism_new)
plot(prism_PCA)
##-> it can be seen in what way the medicaments and their doses belong to the PCs
```


```{r}
# run PCA with Facto Mine
library(FactoMineR)
prism_PCA2=PCA(prism_new)
```
```{r}
# get variance of new dimenstions
prism_PCA2$eig
```

```{r}
# how much of the variance do the new dimensions explain?
prism_PCA2$var$cos2
```

```{r}
# which medicaments do most correlate to first PC?
dimdesc(prism_PCA2)
```
```{r}
# plot contributions of selected variables
library(factoextra)
fviz_pca_var(prism_PCA2, select.var=list(contrib=4), repel=TRUE)
```
```{r}
# barplot contributions of variables to dimension1
fviz_contrib(prism_PCA, choice="var", axes=2, top=10)

# barplot contributions of varibles to dimension2
fviz_contrib(prism_PCA2, choice="var", axes=2, top=10)
```


```{r}
# contributions of variables
fviz_contrib(prism_PCA, choice="var", axes=1, top=5)
fviz_contrib(prism_PCA, choice="var", axes=2, top=5)
```

```{r}
# Plot for presentation
fviz_pca_ind(prism_PCA2, col.ind="cos2", repel=TRUE)

fviz_pca_ind(prism_PCA, col.ind="cos2", repel=TRUE)



fviz_pca_ind(prism_PCA2, selected.ind=list(cos2=0.8), repel=TRUE)
```
```{r}
# Biplot (induviduals + variables)!
fviz_pca_biplot(prism_PCA, axes=c(1,2), geom=c("point"), geom.var=(""),title = ("PCA - Biplot"))
```


```{r}
# choose optimum number of PCs via Scree test
fviz_screeplot(prism_PCA2, ncp=5)
##-> 2 dimensions optimal

fviz_screeplot(prism_PCA, ncp=5)

##-> 3 dimensions optimal
```

```{r}
# find optimal number of PCs via Kaiser-Guttman rule
summary(prism_PCA2)
get_eigenvalue(prism_PCA2)

```


















```{r}
###??????????????????????????????
nPCs=estim_ncpPCA(prism_lung, ncp.min=0, ncp.max=100, method="Regularized", scale=TRUE, method.cv="gcv")
nPCs$ncp

completed=imputePCA(prism_lung, ncp=nPCs$ncp, scale=TRUE)
```

```{r}
# question for tutorium

# use library(missMDA)

library(missMDA)
## only use first 500 columns
### number of missing values
sum(is.na(prism_lung[,1:500]))

### optimal number of dimensions for imputation
ncp=estim_ncpPCA(prism_lung[,1:500])
ncp

### data imputation
complete=imputePCA(prism_lung[,1:500], ncp=ncp$ncp, scale=TRUE)

complete
```
```{r}
complete
as.data.frame(complete)
```


```{r}
# do PCA with completed data
library(FactoMineR)
lung_pca=PCA(complete$completeObs)
```


```{r}
# PCA
str(complete)
class(complete)
prcomp(complete)
```


```{r}
# run PCA
library(FactoMineR)
lung_pca=PCA(complete$completeObs)
```


```{r}
# compute variance of eigenvalues
lung_pca$eig

lung_pca$var$cos2
```


```{r}
lung_pca$var$contrib
```
```{r}
dimdesc(lung_pca)
```
```{r}
# install.packages("devtools")
library("devtools")
install_github("kassambara/factoextra")


library("factoextra")
fviz_pca_var(lung_pca, col.var="contrib", repel=TRUE)
```
```{r}
# get eigenvalues bigger than 1
summary(lung_pca)
lung_pca$eig
get_eigenvalue(lung_pca)
```
```{r}
# 
library(paran)
paran(lung_pca, graph=TRUE)
```


```{r}
# run PCA with prcomp()
prcomp(complete)


```


```{r}
estim_ncpPCA(prism_lung)
```

```{r}
# imupting missing values with pcaMethods
# library(pcaMethods)
##-> not possible with this version of r!
imputePCA(prism_lung, scale=TRUE, )
```

```{r}
# use prcomp for PCA
prcomp(prism_lung, na.rm)
```
```{r}
# use hotdeck() for imputing missing data
prism_lung_imputed=hot.deck(prism_lung)


```
```{r}
install.packages("pcaMethods")

```
```{r}
chooseCRANmirror()
```

```{r}
kNN(prism_lung)
```
